name: multiviewica_delay

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setting Up Conda multiviewica_delay Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        python-version: '3.9'
        activate-environment: multiviewica_delay
        auto-activate-base: false
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 multiviewica_delay *.py --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 multiviewica_delay *.py --count --exit-zero --statistics
    - name: Tests
      run: |
        pytest multiviewica_delay --cov-report term --cov=multiviewica_delay
